namespace GOC.UISystem.Editor
{
    public static class TemplateStrings
    {
        public const string ScreenTemplate =
@"using GOC.UISystem;

namespace {NAMESPACE}
{
    public class {NAME}Screen : UIScreen
    {
    }
}
";

        public const string ScreenWithDataTemplate =
@"using GOC.UISystem;

namespace {NAMESPACE}
{
    public class {NAME}Screen : UIScreen
    {
        public override void OnShow<TData>(TData data)
        {
            if (data is {NAME}Data screenData)
            {
                // TODO: Use screenData
            }
        }
    }
}
";

        public const string ScreenDataTemplate =
@"namespace {NAMESPACE}
{
    public struct {NAME}Data
    {
    }
}
";

        public const string PopupTemplate =
@"using GOC.UISystem;

namespace {NAMESPACE}
{
    public class {NAME}Popup : UIPopup
    {
    }
}
";

        public const string PopupWithDataTemplate =
@"using GOC.UISystem;

namespace {NAMESPACE}
{
    public class {NAME}Popup : UIPopup
    {
        public override void OnShow<TData>(TData data)
        {
            if (data is {NAME}Data popupData)
            {
                // TODO: Use popupData
            }
        }

        public override void OnDismiss()
        {
        }
    }
}
";

        public const string PopupDataTemplate =
@"namespace {NAMESPACE}
{
    public struct {NAME}Data
    {
    }
}
";

        public const string ScreenIdsTemplate =
@"// <auto-generated>
// This file is auto-generated by UISystem Editor Tools. Do not edit manually.
// </auto-generated>

using GOC.UISystem;

namespace {NAMESPACE}
{
    public enum ScreenIdEnum
    {
        None = 0,
{ENUM_ENTRIES}
    }

    public static class ScreenIds
    {
        public static readonly ScreenId None = new ScreenId("""");
{STATIC_ENTRIES}
    }

    public static class ScreenIdExtensions
    {
        public static ScreenId ToScreenId(this ScreenIdEnum value) => value switch
        {
{SWITCH_ENTRIES}
            _ => ScreenIds.None
        };
    }
}
";

        public const string PopupIdsTemplate =
@"// <auto-generated>
// This file is auto-generated by UISystem Editor Tools. Do not edit manually.
// </auto-generated>

using GOC.UISystem;

namespace {NAMESPACE}
{
    public enum PopupIdEnum
    {
        None = 0,
{ENUM_ENTRIES}
    }

    public static class PopupIds
    {
        public static readonly PopupId None = new PopupId("""");
{STATIC_ENTRIES}
    }

    public static class PopupIdExtensions
    {
        public static PopupId ToPopupId(this PopupIdEnum value) => value switch
        {
{SWITCH_ENTRIES}
            _ => PopupIds.None
        };
    }
}
";
    }
}
